[project]
name = "vnpy_ctp"
version = "6.7.2.1"
description = "CTP gateway for vn.py quant trading framework."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Xiaoyou Chen", email = "xiaoyou.chen@mail.vnpy.com"}
]
keywords = ["quant", "quantitative", "investment", "trading", "algotrading", "ctp"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Office/Business :: Financial :: Investment",
    "Programming Language :: Python :: Implementation :: CPython",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Chinese (Simplified)"
]
dependencies = [
    "importlib_metadata"
]

[project.urls]
"Homepage" = "https://www.vnpy.com"
"Repository" = "https://github.com/vnpy/vnpy_ctp"

[build-system]
requires = [
    "meson-python>=0.13.1",
    "ninja>=1.8.2",
    "wheel>=0.38.0",
    "setuptools>=42.0.0",
    "pybind11>=2.9.0",
]
build-backend = "mesonpy"

[tool.mesonpy]
limited-api = false
# Keeping C++ extensions fully visible for debugging purposes
compile-args = []
# Skip dist process to avoid Git issues
skip-dist = true
skip-sdist = true

[tool.mesonpy.module]
packages = ["vnpy_ctp"]
include-package-data = true

[tool.mesonpy.meson-args]
# Pass additional arguments to meson setup
setup = ["--buildtype=release", "--vsenv"]

[tool.mesonpy.args]
compile = ["-utf8", "-DPYBIND11_USE_SMART_HOLDER_AS_DEFAULT", "-Iext/pybind11/include/"] 